import 'package:flutter/material.dart';

class BelajarListSeparated extends StatelessWidget {
  BelajarListSeparated({super.key});

  final List<Color> colorList = [
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
    Colors.blue,
    Colors.amber,
    Colors.red,
  ];

  final List<String> textList = [
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
  ];

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      height: double.infinity,
      child: ListView.separated(
        scrollDirection: Axis.vertical,
        itemCount: colorList.length,
        separatorBuilder: (context, index) {
          return Divider(
            color: Colors.black,
            indent: 10,
            endIndent: 10,
          );
        },
        itemBuilder: (context, index) {
          return Container(
            margin: EdgeInsets.all(10),
            height: 300,
            width: 200,
            color: colorList[index],
            child: Center(
              child: Text(
                textList[index],
                style: TextStyle(fontSize: 32, fontWeight: FontWeight.bold),
              ),
            ),
          );
        },
      ),
    );
  }
}
